class Aeroelasticity:
    """Variable names for the preliminary aeroelasticity external subsystem."""

    FRONT_SPAR_FRACTION = 'aeroelasticity:front_spar_fraction'
    REAR_SPAR_FRACTION = 'aeroelasticity:rear_spar_fraction'
    ELASTIC_AXIS_FRACTION = 'aeroelasticity:elastic_axis_fraction'
    AERODYNAMIC_CENTER_FRACTION = 'aeroelasticity:aerodynamic_center_fraction'
    AERO_CENTER_TO_EA_FRACTION = 'aeroelasticity:aero_center_to_ea_fraction'
    CONTROL_CHORD_FRACTION = 'aeroelasticity:control_chord_fraction'
    CONTROL_HINGE_FRACTION = 'aeroelasticity:control_hinge_fraction'
    CONTROL_CG_FROM_HINGE_FRACTION = 'aeroelasticity:control_cg_from_hinge_fraction'

    SKIN_THICKNESS = 'aeroelasticity:skin_thickness'
    SPAR_THICKNESS = 'aeroelasticity:spar_thickness'
    STRUCTURAL_THICKNESS_TO_CHORD = 'aeroelasticity:structural_thickness_to_chord'
    BOX_HEIGHT_FRACTION = 'aeroelasticity:box_height_fraction'
    YOUNGS_MODULUS = 'aeroelasticity:youngs_modulus'
    SHEAR_MODULUS = 'aeroelasticity:shear_modulus'
    MATERIAL_DENSITY = 'aeroelasticity:material_density'
    TENSILE_ALLOWABLE = 'aeroelasticity:tensile_allowable'
    COMPRESSIVE_ALLOWABLE = 'aeroelasticity:compressive_allowable'
    SHEAR_ALLOWABLE = 'aeroelasticity:shear_allowable'
    STRENGTH_SAFETY_FACTOR = 'aeroelasticity:strength_safety_factor'

    WINGBOX_WIDTH = 'aeroelasticity:wingbox_width'
    WINGBOX_HEIGHT = 'aeroelasticity:wingbox_height'
    WINGBOX_AREA = 'aeroelasticity:wingbox_area'
    BENDING_INERTIA = 'aeroelasticity:bending_inertia'
    TORSION_CONSTANT = 'aeroelasticity:torsion_constant'
    BENDING_STIFFNESS = 'aeroelasticity:EI'
    TORSIONAL_RIGIDITY = 'aeroelasticity:GJ'
    TORSIONAL_STIFFNESS = 'aeroelasticity:torsional_stiffness'
    BENDING_STIFFNESS_PLUNGE = 'aeroelasticity:bending_stiffness_plunge'

    LIFT_CURVE_SLOPE = 'aeroelasticity:lift_curve_slope'
    CONTROL_LIFT_DERIVATIVE = 'aeroelasticity:control_lift_derivative'
    CONTROL_MOMENT_DERIVATIVE = 'aeroelasticity:control_moment_derivative'
    DESIGN_SPEED = 'aeroelasticity:design_speed'
    REQUIRED_SPEED = 'aeroelasticity:required_speed'
    AIR_DENSITY = 'aeroelasticity:air_density'

    DIVERGENCE_DYNAMIC_PRESSURE = 'aeroelasticity:divergence_dynamic_pressure'
    DIVERGENCE_SPEED = 'aeroelasticity:divergence_speed'
    DIVERGENCE_SPEED_MARGIN = 'aeroelasticity:divergence_speed_margin'
    REVERSAL_DYNAMIC_PRESSURE = 'aeroelasticity:reversal_dynamic_pressure'
    REVERSAL_SPEED = 'aeroelasticity:reversal_speed'
    REVERSAL_SPEED_MARGIN = 'aeroelasticity:reversal_speed_margin'
    CONTROL_EFFECTIVENESS = 'aeroelasticity:control_effectiveness'

    MASS_PER_UNIT_SPAN = 'aeroelasticity:mass_per_unit_span'
    PITCH_INERTIA_PER_UNIT_SPAN = 'aeroelasticity:pitch_inertia_per_unit_span'
    CONTROL_INERTIA_PER_UNIT_SPAN = 'aeroelasticity:control_inertia_per_unit_span'
    PITCH_STATIC_UNBALANCE = 'aeroelasticity:pitch_static_unbalance'
    CONTROL_STATIC_UNBALANCE = 'aeroelasticity:control_static_unbalance'
    CONTROL_STIFFNESS = 'aeroelasticity:control_stiffness'
    STRUCTURAL_DAMPING_RATIO = 'aeroelasticity:structural_damping_ratio'
    CONTROL_MOMENT_ALPHA_DERIVATIVE = 'aeroelasticity:control_moment_alpha_derivative'
    HINGE_MOMENT_ALPHA_DERIVATIVE = 'aeroelasticity:hinge_moment_alpha_derivative'
    HINGE_MOMENT_CONTROL_DERIVATIVE = 'aeroelasticity:hinge_moment_control_derivative'
    FLUTTER_MAX_SPEED = 'aeroelasticity:flutter_max_speed'
    FLUTTER_SPEED = 'aeroelasticity:flutter_speed'
    FLUTTER_DYNAMIC_PRESSURE = 'aeroelasticity:flutter_dynamic_pressure'
    FLUTTER_MARGIN = 'aeroelasticity:flutter_margin'
    FLUTTER_SPEED_MARGIN = 'aeroelasticity:flutter_speed_margin'
    MAX_REAL_EIGENVALUE_AT_DESIGN = 'aeroelasticity:max_real_eigenvalue_at_design'
    PK_FLUTTER_SPEED = 'aeroelasticity:pk_flutter_speed'
    PK_FLUTTER_FREQUENCY = 'aeroelasticity:pk_flutter_frequency'
    PK_FLUTTER_DYNAMIC_PRESSURE = 'aeroelasticity:pk_flutter_dynamic_pressure'
    PK_FLUTTER_SPEED_MARGIN = 'aeroelasticity:pk_flutter_speed_margin'
    PK_CRITICAL_MODE = 'aeroelasticity:pk_critical_mode'
    PK_CONVERGED = 'aeroelasticity:pk_converged'
    PK_MODE_DAMPING = 'aeroelasticity:pk_mode_damping'
    PK_MODE_FREQUENCY = 'aeroelasticity:pk_mode_frequency'
    BEAM_MODAL_BENDING_FREQUENCY = 'aeroelasticity:beam_modal_bending_frequency'
    BEAM_MODAL_TORSION_FREQUENCY = 'aeroelasticity:beam_modal_torsion_frequency'
    BEAM_MODAL_FLUTTER_SPEED = 'aeroelasticity:beam_modal_flutter_speed'
    BEAM_MODAL_FLUTTER_SPEED_MARGIN = 'aeroelasticity:beam_modal_flutter_speed_margin'
    BEAM_MODAL_MAX_REAL_EIGENVALUE_AT_DESIGN = (
        'aeroelasticity:beam_modal_max_real_eigenvalue_at_design'
    )
    BEAM_MODAL_CRITICAL_MODE = 'aeroelasticity:beam_modal_critical_mode'
    BEAM_MODAL_PK_FLUTTER_SPEED = 'aeroelasticity:beam_modal_pk_flutter_speed'
    BEAM_MODAL_PK_FLUTTER_FREQUENCY = 'aeroelasticity:beam_modal_pk_flutter_frequency'
    BEAM_MODAL_PK_FLUTTER_SPEED_MARGIN = (
        'aeroelasticity:beam_modal_pk_flutter_speed_margin'
    )
    BEAM_MODAL_PK_MODE_DAMPING = 'aeroelasticity:beam_modal_pk_mode_damping'
    BEAM_MODAL_PK_MODE_FREQUENCY = 'aeroelasticity:beam_modal_pk_mode_frequency'
    BEAM_MODAL_PK_CONVERGED = 'aeroelasticity:beam_modal_pk_converged'

    BEAM_MODAL_CONTROL_FREQUENCY = 'aeroelasticity:beam_modal_control_frequency'
    BEAM_MODAL_3DOF_PK_FLUTTER_SPEED = 'aeroelasticity:beam_modal_3dof_pk_flutter_speed'
    BEAM_MODAL_3DOF_PK_FLUTTER_FREQUENCY = 'aeroelasticity:beam_modal_3dof_pk_flutter_frequency'
    BEAM_MODAL_3DOF_PK_FLUTTER_SPEED_MARGIN = (
        'aeroelasticity:beam_modal_3dof_pk_flutter_speed_margin'
    )
    BEAM_MODAL_3DOF_PK_CONVERGED = 'aeroelasticity:beam_modal_3dof_pk_converged'
    BEAM_MODAL_3DOF_PK_MODE_DAMPING = 'aeroelasticity:beam_modal_3dof_pk_mode_damping'
    BEAM_MODAL_3DOF_PK_MODE_FREQUENCY = 'aeroelasticity:beam_modal_3dof_pk_mode_frequency'

    VTP_CHORDWISE_CG_FRACTION = 'aeroelasticity:vtp_chordwise_cg_fraction'
    VTP_ROOT_LE_X_OFFSET = 'aeroelasticity:vtp_root_le_x_offset'
    VTP_AREAL_DENSITY = 'aeroelasticity:vtp_areal_density'
    VTP_TIP_PANEL_COUNT = 'aeroelasticity:vtp_tip_panel_count'
    VTP_TIP_MASS = 'aeroelasticity:vtp_tip_mass'
    VTP_TIP_PITCH_INERTIA = 'aeroelasticity:vtp_tip_pitch_inertia'
    VTP_EQUIVALENT_MASS_PER_UNIT_SPAN = 'aeroelasticity:vtp_equivalent_mass_per_unit_span'
    VTP_PITCH_INERTIA_PER_UNIT_SPAN = 'aeroelasticity:vtp_pitch_inertia_per_unit_span'
    VTP_PITCH_STATIC_UNBALANCE = 'aeroelasticity:vtp_pitch_static_unbalance'
    VTP_CG_X_FROM_WING_TIP_LE = 'aeroelasticity:vtp_cg_x_from_wing_tip_le'
    VTP_CG_Z_ABS = 'aeroelasticity:vtp_cg_z_abs'
    VTP_DX_TO_ELASTIC_AXIS = 'aeroelasticity:vtp_dx_to_elastic_axis'

    LOAD_FACTOR = 'aeroelasticity:load_factor'
    LOAD_LIFT_COEFFICIENT = 'aeroelasticity:load_lift_coefficient'
    SPANWISE_STATIONS = 'aeroelasticity:spanwise_stations'
    SPANWISE_CHORD = 'aeroelasticity:spanwise_chord'
    SPANWISE_WINGBOX_WIDTH = 'aeroelasticity:spanwise_wingbox_width'
    SPANWISE_WINGBOX_HEIGHT = 'aeroelasticity:spanwise_wingbox_height'
    SPANWISE_BENDING_STIFFNESS = 'aeroelasticity:spanwise_EI'
    SPANWISE_TORSIONAL_RIGIDITY = 'aeroelasticity:spanwise_GJ'
    SPANWISE_MASS_PER_UNIT_SPAN = 'aeroelasticity:spanwise_mass_per_unit_span'
    SPANWISE_PITCH_INERTIA_PER_UNIT_SPAN = 'aeroelasticity:spanwise_pitch_inertia_per_unit_span'
    SPANWISE_ADDED_MASS_PER_UNIT_SPAN = 'aeroelasticity:spanwise_added_mass_per_unit_span'
    SPANWISE_TOTAL_MASS_PER_UNIT_SPAN = 'aeroelasticity:spanwise_total_mass_per_unit_span'
    SPANWISE_TOTAL_PITCH_INERTIA_PER_UNIT_SPAN = (
        'aeroelasticity:spanwise_total_pitch_inertia_per_unit_span'
    )
    SPANWISE_TOTAL_HALF_WING_MASS = 'aeroelasticity:spanwise_total_half_wing_mass'
    ENGINE_MASS = 'aeroelasticity:engine_mass'
    ENGINE_SPAN_FRACTION = 'aeroelasticity:engine_span_fraction'
    ENGINE_X_OFFSET_TO_EA = 'aeroelasticity:engine_x_offset_to_ea'
    FUEL_MASS = 'aeroelasticity:fuel_mass'
    FUEL_SPAN_FRACTION = 'aeroelasticity:fuel_span_fraction'
    FUEL_X_OFFSET_TO_EA = 'aeroelasticity:fuel_x_offset_to_ea'
    SERVO_MASS = 'aeroelasticity:servo_mass'
    SERVO_SPAN_FRACTION = 'aeroelasticity:servo_span_fraction'
    SERVO_X_OFFSET_TO_EA = 'aeroelasticity:servo_x_offset_to_ea'
    ELEVON_MASS = 'aeroelasticity:elevon_mass'
    ELEVON_SPAN_START_FRACTION = 'aeroelasticity:elevon_span_start_fraction'
    ELEVON_SPAN_END_FRACTION = 'aeroelasticity:elevon_span_end_fraction'
    ELEVON_CG_FRACTION = 'aeroelasticity:elevon_cg_fraction'
    SCHRENK_LIFT_PER_UNIT_SPAN = 'aeroelasticity:schrenk_lift_per_unit_span'
    SCHRENK_SHEAR_FORCE = 'aeroelasticity:schrenk_shear_force'
    SCHRENK_BENDING_MOMENT = 'aeroelasticity:schrenk_bending_moment'
    SCHRENK_TORQUE = 'aeroelasticity:schrenk_torque'
    SPANWISE_SLOPE = 'aeroelasticity:spanwise_slope'
    SPANWISE_DEFLECTION = 'aeroelasticity:spanwise_deflection'
    SPANWISE_TWIST = 'aeroelasticity:spanwise_twist'
    SPANWISE_TWIST_DEG = 'aeroelasticity:spanwise_twist_deg'
    SCHRENK_TIP_DEFLECTION = 'aeroelasticity:schrenk_tip_deflection'
    SCHRENK_TIP_TWIST = 'aeroelasticity:schrenk_tip_twist'
    SCHRENK_TIP_TWIST_DEG = 'aeroelasticity:schrenk_tip_twist_deg'
    CONSTANT_LIFT_PER_UNIT_SPAN = 'aeroelasticity:constant_lift_per_unit_span'
    CONSTANT_TOTAL_LIFT = 'aeroelasticity:constant_total_lift'
    ROOT_BENDING_MOMENT = 'aeroelasticity:root_bending_moment'
    ROOT_TORQUE = 'aeroelasticity:root_torque'
    TIP_DEFLECTION = 'aeroelasticity:tip_deflection'
    TIP_TWIST = 'aeroelasticity:tip_twist'
    TIP_TWIST_DEG = 'aeroelasticity:tip_twist_deg'
    ROOT_BENDING_STRESS = 'aeroelasticity:root_bending_stress'
    TORSION_SHEAR_STRESS = 'aeroelasticity:torsion_shear_stress'
    BENDING_STRENGTH_MARGIN = 'aeroelasticity:bending_strength_margin'
    TORSION_STRENGTH_MARGIN = 'aeroelasticity:torsion_strength_margin'
    MIN_STRENGTH_MARGIN = 'aeroelasticity:min_strength_margin'
