class Aeroelasticity:
    """Variable names for the preliminary aeroelasticity external subsystem."""

    FRONT_SPAR_FRACTION = 'aeroelasticity:front_spar_fraction'
    REAR_SPAR_FRACTION = 'aeroelasticity:rear_spar_fraction'
    ELASTIC_AXIS_FRACTION = 'aeroelasticity:elastic_axis_fraction'
    AERODYNAMIC_CENTER_FRACTION = 'aeroelasticity:aerodynamic_center_fraction'
    AERO_CENTER_TO_EA_FRACTION = 'aeroelasticity:aero_center_to_ea_fraction'
    CONTROL_CHORD_FRACTION = 'aeroelasticity:control_chord_fraction'
    CONTROL_HINGE_FRACTION = 'aeroelasticity:control_hinge_fraction'
    CONTROL_CG_FROM_HINGE_FRACTION = 'aeroelasticity:control_cg_from_hinge_fraction'

    SKIN_THICKNESS = 'aeroelasticity:skin_thickness'
    SPAR_THICKNESS = 'aeroelasticity:spar_thickness'
    BOX_HEIGHT_FRACTION = 'aeroelasticity:box_height_fraction'
    YOUNGS_MODULUS = 'aeroelasticity:youngs_modulus'
    SHEAR_MODULUS = 'aeroelasticity:shear_modulus'
    MATERIAL_DENSITY = 'aeroelasticity:material_density'
    TENSILE_ALLOWABLE = 'aeroelasticity:tensile_allowable'
    COMPRESSIVE_ALLOWABLE = 'aeroelasticity:compressive_allowable'
    SHEAR_ALLOWABLE = 'aeroelasticity:shear_allowable'
    STRENGTH_SAFETY_FACTOR = 'aeroelasticity:strength_safety_factor'

    WINGBOX_WIDTH = 'aeroelasticity:wingbox_width'
    WINGBOX_HEIGHT = 'aeroelasticity:wingbox_height'
    WINGBOX_AREA = 'aeroelasticity:wingbox_area'
    BENDING_INERTIA = 'aeroelasticity:bending_inertia'
    TORSION_CONSTANT = 'aeroelasticity:torsion_constant'
    BENDING_STIFFNESS = 'aeroelasticity:EI'
    TORSIONAL_RIGIDITY = 'aeroelasticity:GJ'
    TORSIONAL_STIFFNESS = 'aeroelasticity:torsional_stiffness'
    BENDING_STIFFNESS_PLUNGE = 'aeroelasticity:bending_stiffness_plunge'

    LIFT_CURVE_SLOPE = 'aeroelasticity:lift_curve_slope'
    CONTROL_LIFT_DERIVATIVE = 'aeroelasticity:control_lift_derivative'
    CONTROL_MOMENT_DERIVATIVE = 'aeroelasticity:control_moment_derivative'
    DESIGN_SPEED = 'aeroelasticity:design_speed'
    REQUIRED_SPEED = 'aeroelasticity:required_speed'
    AIR_DENSITY = 'aeroelasticity:air_density'

    DIVERGENCE_DYNAMIC_PRESSURE = 'aeroelasticity:divergence_dynamic_pressure'
    DIVERGENCE_SPEED = 'aeroelasticity:divergence_speed'
    DIVERGENCE_SPEED_MARGIN = 'aeroelasticity:divergence_speed_margin'
    REVERSAL_DYNAMIC_PRESSURE = 'aeroelasticity:reversal_dynamic_pressure'
    REVERSAL_SPEED = 'aeroelasticity:reversal_speed'
    REVERSAL_SPEED_MARGIN = 'aeroelasticity:reversal_speed_margin'
    CONTROL_EFFECTIVENESS = 'aeroelasticity:control_effectiveness'

    MASS_PER_UNIT_SPAN = 'aeroelasticity:mass_per_unit_span'
    PITCH_INERTIA_PER_UNIT_SPAN = 'aeroelasticity:pitch_inertia_per_unit_span'
    CONTROL_INERTIA_PER_UNIT_SPAN = 'aeroelasticity:control_inertia_per_unit_span'
    PITCH_STATIC_UNBALANCE = 'aeroelasticity:pitch_static_unbalance'
    CONTROL_STATIC_UNBALANCE = 'aeroelasticity:control_static_unbalance'
    CONTROL_STIFFNESS = 'aeroelasticity:control_stiffness'
    STRUCTURAL_DAMPING_RATIO = 'aeroelasticity:structural_damping_ratio'
    CONTROL_MOMENT_ALPHA_DERIVATIVE = 'aeroelasticity:control_moment_alpha_derivative'
    HINGE_MOMENT_ALPHA_DERIVATIVE = 'aeroelasticity:hinge_moment_alpha_derivative'
    HINGE_MOMENT_CONTROL_DERIVATIVE = 'aeroelasticity:hinge_moment_control_derivative'
    FLUTTER_MAX_SPEED = 'aeroelasticity:flutter_max_speed'
    FLUTTER_SPEED = 'aeroelasticity:flutter_speed'
    FLUTTER_DYNAMIC_PRESSURE = 'aeroelasticity:flutter_dynamic_pressure'
    FLUTTER_MARGIN = 'aeroelasticity:flutter_margin'
    FLUTTER_SPEED_MARGIN = 'aeroelasticity:flutter_speed_margin'
    MAX_REAL_EIGENVALUE_AT_DESIGN = 'aeroelasticity:max_real_eigenvalue_at_design'
    PK_FLUTTER_SPEED = 'aeroelasticity:pk_flutter_speed'
    PK_FLUTTER_FREQUENCY = 'aeroelasticity:pk_flutter_frequency'
    PK_FLUTTER_DYNAMIC_PRESSURE = 'aeroelasticity:pk_flutter_dynamic_pressure'
    PK_FLUTTER_SPEED_MARGIN = 'aeroelasticity:pk_flutter_speed_margin'
    PK_CRITICAL_MODE = 'aeroelasticity:pk_critical_mode'
    PK_CONVERGED = 'aeroelasticity:pk_converged'
    PK_MODE_DAMPING = 'aeroelasticity:pk_mode_damping'
    PK_MODE_FREQUENCY = 'aeroelasticity:pk_mode_frequency'

    VTP_CHORDWISE_CG_FRACTION = 'aeroelasticity:vtp_chordwise_cg_fraction'
    VTP_ROOT_LE_X_OFFSET = 'aeroelasticity:vtp_root_le_x_offset'
    VTP_EQUIVALENT_MASS_PER_UNIT_SPAN = 'aeroelasticity:vtp_equivalent_mass_per_unit_span'
    VTP_PITCH_INERTIA_PER_UNIT_SPAN = 'aeroelasticity:vtp_pitch_inertia_per_unit_span'
    VTP_PITCH_STATIC_UNBALANCE = 'aeroelasticity:vtp_pitch_static_unbalance'
    VTP_CG_X_FROM_WING_TIP_LE = 'aeroelasticity:vtp_cg_x_from_wing_tip_le'
    VTP_CG_Z_ABS = 'aeroelasticity:vtp_cg_z_abs'
    VTP_DX_TO_ELASTIC_AXIS = 'aeroelasticity:vtp_dx_to_elastic_axis'

    LOAD_FACTOR = 'aeroelasticity:load_factor'
    LOAD_LIFT_COEFFICIENT = 'aeroelasticity:load_lift_coefficient'
    CONSTANT_LIFT_PER_UNIT_SPAN = 'aeroelasticity:constant_lift_per_unit_span'
    CONSTANT_TOTAL_LIFT = 'aeroelasticity:constant_total_lift'
    ROOT_BENDING_MOMENT = 'aeroelasticity:root_bending_moment'
    ROOT_TORQUE = 'aeroelasticity:root_torque'
    TIP_DEFLECTION = 'aeroelasticity:tip_deflection'
    TIP_TWIST = 'aeroelasticity:tip_twist'
    TIP_TWIST_DEG = 'aeroelasticity:tip_twist_deg'
    ROOT_BENDING_STRESS = 'aeroelasticity:root_bending_stress'
    TORSION_SHEAR_STRESS = 'aeroelasticity:torsion_shear_stress'
    BENDING_STRENGTH_MARGIN = 'aeroelasticity:bending_strength_margin'
    TORSION_STRENGTH_MARGIN = 'aeroelasticity:torsion_strength_margin'
    MIN_STRENGTH_MARGIN = 'aeroelasticity:min_strength_margin'
